import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, Users, CalendarCheck, MessageSquare, LogOut, ShieldCheck, Search, RefreshCw, Trash2, CheckCircle2, Clock3 } from 'lucide-react';

type Customer = { _id:string; email:string; name:string; createdAt:string; lastLoginAt:string; loginCount:number };
type Booking = { _id:string; bookingId:string; yatraTitle:string; customerName:string; customerPhone:string; customerEmail?:string; travelDate:string; guestsCount:number; totalEstimatedAmount:number; status:string; createdAt:string; notes?:string };
type Enquiry = { _id:string; fullName:string; phone:string; email?:string; selectedYatra:string; travelDate:string; travelersCount:number; status:string; createdAt:string };

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
const date=(v:string)=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
async function api(url:string, options:RequestInit={}) { const res=await fetch(url,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}}); let data:any={}; try{data=await res.json();}catch{} if(!res.ok) throw new Error(data.message||'Request failed'); return data; }

export const AdminDashboard:React.FC=()=>{
  const [authenticated,setAuthenticated]=useState<boolean|null>(null); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [tab,setTab]=useState<'overview'|'customers'|'bookings'|'enquiries'>('overview');
  const [customers,setCustomers]=useState<Customer[]>([]); const [bookings,setBookings]=useState<Booking[]>([]); const [enquiries,setEnquiries]=useState<Enquiry[]>([]); const [db,setDb]=useState<any>(null); const [query,setQuery]=useState('');

  const load=async()=>{ try { const [c,b,e,d]=await Promise.all([api('/api/customers'),api('/api/bookings'),api('/api/enquiries'),api('/api/database/status')]); setCustomers(c.data||[]);setBookings(b.data||[]);setEnquiries(e.data||[]);setDb(d);setAuthenticated(true); } catch(err:any){ if(String(err.message).toLowerCase().includes('unauthorized')) setAuthenticated(false); else setError(err.message); } };
  useEffect(()=>{ api('/api/admin/me').then(()=>{setAuthenticated(true);load();}).catch(()=>setAuthenticated(false)); },[]);
  const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password})});setPassword('');setAuthenticated(true);await load();}catch(err:any){setError(err.message);}finally{setBusy(false);}};
  const logout=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});setAuthenticated(false);window.history.replaceState({},'', '/admin');};
  const updateStatus=async(kind:'bookings'|'enquiries',id:string,status:string)=>{try{await api(`/api/${kind}/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load();}catch(err:any){setError(err.message);}};
  const remove=async(kind:'bookings'|'enquiries',id:string)=>{if(!confirm('Delete this record? This cannot be undone.'))return;try{await api(`/api/${kind}/${id}`,{method:'DELETE'});await load();}catch(err:any){setError(err.message);}};

  const filteredCustomers=useMemo(()=>customers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase())),[customers,query]);
  const filteredBookings=useMemo(()=>bookings.filter(b=>`${b.bookingId} ${b.customerName} ${b.customerPhone} ${b.yatraTitle}`.toLowerCase().includes(query.toLowerCase())),[bookings,query]);
  const filteredEnquiries=useMemo(()=>enquiries.filter(e=>`${e.fullName} ${e.phone} ${e.email||''} ${e.selectedYatra}`.toLowerCase().includes(query.toLowerCase())),[enquiries,query]);

  if(authenticated===null) return <div className="min-h-screen bg-slate-950 text-white grid place-items-center">Checking secure admin session…</div>;
  if(!authenticated) return <div className="min-h-screen bg-[#0b1224] grid place-items-center p-4"><form onSubmit={login} className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl text-slate-900"><div className="w-12 h-12 rounded-2xl bg-[#cca042] grid place-items-center mb-5"><ShieldCheck/></div><h1 className="text-3xl font-bold font-serif">Purva Yatra Admin</h1><p className="mt-2 text-slate-500">Secure management portal</p><label className="block mt-8 text-sm font-semibold">Admin password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border p-3 outline-none focus:ring-2 focus:ring-[#cca042]" placeholder="Enter server admin secret" /></label>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-[#0b1224] text-white py-3 font-semibold disabled:opacity-60">{busy?'Signing in…':'Sign in securely'}</button><p className="mt-4 text-xs text-slate-400">The password is checked only on the server. It is never stored in the browser.</p></form></div>;

  const nav=[['overview','Overview',BarChart3],['customers','Customers',Users],['bookings','Bookings',CalendarCheck],['enquiries','Enquiries',MessageSquare]] as const;
  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <aside className="fixed inset-y-0 left-0 w-64 bg-[#0b1224] text-white hidden md:flex flex-col"><div className="p-6"><div className="text-[#cca042] text-xs font-bold tracking-[.25em]">PURVA YATRA</div><div className="text-2xl font-serif mt-1">Admin Portal</div></div><nav className="px-3 space-y-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setTab(id);setQuery('')}} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left ${tab===id?'bg-white/10 text-[#cca042]':'text-slate-300 hover:bg-white/5'}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-auto p-4"><button onClick={logout} className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-slate-300 hover:bg-white/5"><LogOut size={18}/>Sign out</button></div></aside>
    <main className="md:ml-64 min-h-screen"><header className="sticky top-0 z-20 bg-white/90 backdrop-blur border-b px-4 md:px-8 py-4 flex items-center justify-between"><div><h1 className="text-2xl font-bold capitalize">{tab}</h1><p className="text-xs text-slate-500">Private admin area • server-authenticated</p></div><div className="flex items-center gap-2"><button onClick={load} className="p-2 rounded-lg border hover:bg-slate-50" title="Refresh"><RefreshCw size={18}/></button><button onClick={logout} className="md:hidden p-2 rounded-lg border"><LogOut size={18}/></button></div></header>
    <div className="p-4 md:p-8">
      {error&&<div className="mb-5 rounded-xl bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{error}</div>}
      {tab==='overview'&&<><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[[Users,'Customers',customers.length],[CalendarCheck,'Bookings',bookings.length],[MessageSquare,'Enquiries',enquiries.length],[Clock3,'Total customer logins',customers.reduce((a,c)=>a+c.loginCount,0)]] .map(([Icon,label,value]:any)=><div className="bg-white rounded-2xl border p-5 shadow-sm" key={label}><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="text-3xl font-bold mt-2">{value}</p></div><div className="p-3 rounded-xl bg-slate-100"><Icon size={20}/></div></div></div>)}</div><div className="grid lg:grid-cols-2 gap-5 mt-6"><section className="bg-white rounded-2xl border p-5"><h2 className="font-bold">Recent customers</h2><div className="mt-4 space-y-3">{customers.slice(0,5).map(c=><div className="flex justify-between border-b pb-3" key={c._id}><div><div className="font-semibold">{c.name||'Pilgrim'}</div><div className="text-sm text-slate-500">{c.email}</div></div><div className="text-xs text-slate-400">{date(c.lastLoginAt)}</div></div>)}{!customers.length&&<p className="text-slate-500 text-sm">No customer logins yet.</p>}</div></section><section className="bg-white rounded-2xl border p-5"><h2 className="font-bold">Database</h2><div className="mt-4 flex items-center gap-3"><div className={`w-3 h-3 rounded-full ${db?.connected?'bg-green-500':'bg-amber-500'}`}/><span>{db?.connected?'MongoDB connected':'Local development store'}</span></div><p className="text-sm text-slate-500 mt-3">{db?.databaseName||'—'}</p></section></div></>}
      {tab!=='overview'&&<div className="bg-white rounded-2xl border overflow-hidden"><div className="p-4 border-b flex gap-3"><div className="relative flex-1 max-w-xl"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full border rounded-xl py-2.5 pl-10 pr-3" placeholder={`Search ${tab}…`}/></div></div>
      {tab==='customers'&&<Table headers={['Customer','Email','Registered','Last login','Logins']}>{filteredCustomers.map(c=><tr key={c._id} className="border-b"><td className="px-4 py-4 font-semibold">{c.name||'Pilgrim'}</td><td className="px-4 py-4">{c.email}</td><td className="px-4 py-4 text-sm text-slate-500">{date(c.createdAt)}</td><td className="px-4 py-4 text-sm text-slate-500">{date(c.lastLoginAt)}</td><td className="px-4 py-4">{c.loginCount}</td></tr>)}</Table>}
      {tab==='bookings'&&<Table headers={['Booking','Customer','Yatra','Travel date','Amount','Status','Action']}>{filteredBookings.map(b=><tr key={b._id} className="border-b"><td className="px-4 py-4 font-semibold">{b.bookingId}</td><td className="px-4 py-4"><div>{b.customerName}</div><div className="text-xs text-slate-500">{b.customerPhone}</div></td><td className="px-4 py-4">{b.yatraTitle}</td><td className="px-4 py-4">{b.travelDate||'—'}</td><td className="px-4 py-4">{money(b.totalEstimatedAmount)}</td><td className="px-4 py-4"><select value={b.status} onChange={e=>updateStatus('bookings',b._id,e.target.value)} className="border rounded-lg px-2 py-1 text-sm"><option>New</option><option>Confirmed</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select></td><td className="px-4 py-4"><button onClick={()=>remove('bookings',b._id)} className="text-red-600"><Trash2 size={17}/></button></td></tr>)}</Table>}
      {tab==='enquiries'&&<Table headers={['Customer','Contact','Yatra','Travel date','Status','Action']}>{filteredEnquiries.map(e=><tr key={e._id} className="border-b"><td className="px-4 py-4 font-semibold">{e.fullName}</td><td className="px-4 py-4"><div>{e.phone}</div><div className="text-xs text-slate-500">{e.email||'—'}</div></td><td className="px-4 py-4">{e.selectedYatra}</td><td className="px-4 py-4">{e.travelDate||'—'}</td><td className="px-4 py-4"><select value={e.status} onChange={x=>updateStatus('enquiries',e._id,x.target.value)} className="border rounded-lg px-2 py-1 text-sm"><option>New</option><option>Contacted</option><option>Confirmed</option><option>Closed</option></select></td><td className="px-4 py-4"><button onClick={()=>remove('enquiries',e._id)} className="text-red-600"><Trash2 size={17}/></button></td></tr>)}</Table>}
      </div>}
    </div></main></div>;
};

const Table:React.FC<{headers:string[];children:React.ReactNode}> = ({headers,children})=><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{headers.map(h=><th key={h} className="text-left px-4 py-3 font-semibold text-slate-600 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
